okhv = "2.0"
name = "GliaX-Faceshield"
repo = "https://github.com/GliaX/faceshield"
version = "3.0.0"
release = "https://github.com/GliaX/faceshield"
license = "GPL-3.0-only"
licensor = "Jake Bender, Mike Doell"
organisation = "Glia equal care"
readme = "README.md"
documentation-language = "en-GB"
technology-readiness-level = "OTRL5"
documentation-readiness-level = "ODRL2"
function = "The goal of GliaX-Faceshield is to create a low cost, high quality, reusable face shield that can be quickly deployed."
cpc-patent-class = "A41G"
tsdc = "3DP"
manufacturing-instructions = "/blob/master/instructions_bilingual.png"
user-manual = "/blob/master/instructions.jpg"
