okhv = "2.0"
name = "KORUZA"
repo = "https://github.com/IRNAS/KORUZA"
version = "0.10.0"
release = "https://github.com/IRNAS/KORUZA"
license = "CERN-OHL-1.2"
licensor = "Martin HÃ¤uer"
organisation = "Fraunhofer IPK"
readme = "README.md"
documentation-language = "en-GB"
technology-readiness-level = "OTRL5"
documentation-readiness-level = "ODRL4"
function = "KORUZA innovates the design of a free-space optical communication system reusing mass produced Small Form-factor Pluggable (SFP) electro-optical transceivers, combining the latest advances in low-cost 3D printing using the Fused Deposition Modelling (F DM) method with bare-minimum custom electronics design."
cpc-patent-class = "H04"
tsdc = "STD"
bom = "/blob/master/koruza-v10-BillOfMaterials.ods"
manufacturing-instructions = "/KORUZA-instructions/tree/gh-pages/instructions"
user-manual = "/KORUZA-instructions/blob/gh-pages/user-manual.md"
